"""MkDocs hook: stamp every lab and lecture page with a version derived from git history.

Wired in via `hooks:` in mkdocs.yml. Nothing is stored anywhere -- the version is recomputed on
every build from the commits that touched the page, so it can never drift from what shipped.

Format: yyyy.mm.rev

- yyyy.mm  -- year and month (Mountain time) of the latest commit that touched the page.
- rev      -- how many commits touched the page in that month, so it restarts at 1 each month.
             Each commit counts once, so a push carrying two commits to a lab bumps rev by two.

What counts as "the page":

- A lab (docs/assignments/lab-NN/README.md) is versioned by its whole folder, so a replaced
  screenshot in images/ bumps the lab even when the README is untouched.
- A lecture day (docs/lectures/day-NN.md) is versioned by that page plus the matching
  slides/day-NN/ deck folder, because the deck is what students open from the page.
  Day pages are regenerated by tools/build_schedule.py, but git only records a commit when the
  content actually changed, so regenerating unchanged pages does not bump anything.

A page with no commits yet shows "draft (not yet committed)".

The deploy workflow checks out with fetch-depth: 0; a shallow clone would make every page 1.
"""

from __future__ import annotations

import datetime as _dt
import os
import re
import subprocess

_LAB = re.compile(r"^assignments/(lab-\d+)/README\.md$")
_DAY = re.compile(r"^lectures/(day-\d+)\.md$")
_TZ = "America/Denver"


def _tracked_paths(src_path: str, repo_root: str) -> list[str] | None:
    src_path = src_path.replace(os.sep, "/")
    m = _LAB.match(src_path)
    if m:
        return [f"docs/assignments/{m.group(1)}"]
    m = _DAY.match(src_path)
    if m:
        paths = [f"docs/lectures/{m.group(1)}.md"]
        deck = f"slides/{m.group(1)}"
        if os.path.isdir(os.path.join(repo_root, deck)):
            paths.append(deck)
        return paths
    return None


def _commit_dates(paths: list[str], repo_root: str) -> list[_dt.date]:
    env = dict(os.environ, TZ=_TZ)
    out = subprocess.run(
        ["git", "log", "--no-merges", "--format=%cd", "--date=format-local:%Y-%m-%d", "--", *paths],
        cwd=repo_root, env=env, capture_output=True, text=True, check=False,
    ).stdout.split()
    return [_dt.date.fromisoformat(s) for s in out]


def page_version(src_path: str, repo_root: str) -> tuple[str, _dt.date | None] | None:
    """Return (version, last_updated) for a lab or lecture page, or None for other pages."""
    paths = _tracked_paths(src_path, repo_root)
    if paths is None:
        return None
    dates = _commit_dates(paths, repo_root)
    if not dates:
        return "draft (not yet committed)", None
    latest = dates[0]
    rev = sum(1 for d in dates if (d.year, d.month) == (latest.year, latest.month))
    return f"{latest.year}.{latest.month:02d}.{rev}", latest


def on_page_markdown(markdown: str, page, config, files) -> str:
    repo_root = os.path.dirname(os.path.abspath(config["config_file_path"]))
    result = page_version(page.file.src_path, repo_root)
    if result is None:
        return markdown
    version, updated = result
    page.meta["page_version"] = version
    if updated is None:
        line = f"Version {version}"
    else:
        line = f"Version {version} · Last updated {updated.strftime('%B')} {updated.day}, {updated.year}"
    return markdown.rstrip() + f'\n\n---\n\n<p class="page-version">{line}</p>\n'
